### ISSUE TITLE
Trantor plugin uses deprecated API.

### ISSUE THREAD

**Issue by HackerMadCat** [Wujiaxuan007/trantor-plugin-error-receiver#52]
Intellij IDEA team is going to remove `org.jetbrains.idea.maven.wizards.MavenStructureWizardStep` and `MavenizedStructureWizardStep`, because they duplicates behavior of modern new project wizard.

Please could you remove usages of `MavenStructureWizardStep` in the code base of [Trantor plugin](https://plugins.jetbrains.com/plugin/18960-trantor)? You can use [MavenNewProjectWizardStep](https://github.com/JetBrains/intellij-community/blob/368756e165ef61eb813bb60151fa1fa131ec4acc/plugins/maven/src/main/java/org/jetbrains/idea/maven/wizards/MavenNewProjectWizardStep.kt#L26) instead.

I truncated implementation of `MavenStructureWizardStep` for backward compatibility with Trantor plugin, but I could not test it due to an [issue](https://github.com/Wujiaxuan007/trantor-plugin-error-receiver/issues/51) in this plugin.

**Comment by Wujiaxuan007** [comment]
Sorry, I will modify the code as soon as possible

**Comment by HackerMadCat** [comment]
Thank you!

**Comment by Wujiaxuan007** [comment]
[V0.8.0 ](https://plugins.jetbrains.com/plugin/18960-trantor/versions/) fixes these issues, but it is still under approval.
